name: Auto Release
on:
  push:
    branches: main
  pull_request:
    types: close
    branches: main
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - uses: actions/checkout@v3
      - name: Create Tag
        id: create_tag
        run: |
          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo ${{ env.TAG }}
      - run: git fetch origin ${{ github.event.pull_request.head.ref }}
      - run: git checkout ${{ github.event.pull_request.head.ref }}
      - run: echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'
