name: Auto Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      if: startsWith(github.head_ref, 'release') || startsWith(github.head_ref, 'hotfix')
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: create tag and release
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
