name: Greeting
on: workflow_dispatch

jobs:
  create-auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update authors
          title: 本番リリース
          body: リリース内容を記載してください
          branch: release
          base: main
