name: Create auto Pull Request
on:
  workflow_dispatch:
  push:

jobs:
  create-auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
      - name: check_pr
        run: |
          echo "count=$(gh pr list --search '本番リリース in:title' -B main | wc -l)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: git pull develop diff to release
        if: steps.check_pr.outputs.count == 0
        run: |
         git switch release
         git pull origin develop
         git push origin release
      - name: Create release pr
        if: steps.check_pr.outputs.count == 0
        run: gh pr create -B "main" -t "本番リリース" -b "リリース内容を記載してください"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "#times_nakai",
              "text": "ちゃっす"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
