name: Create auto Pull Request
on:
  workflow_dispatch:
  push:

jobs:
  create-auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - id: check_pr
        name: check_pr
        run: |
          echo "count=$(gh pr list --search '本番リリース in:title' -B main | wc -l)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: git pull develop diff to release
        id: create_pr
        if: steps.check_pr.outputs.count == 0
        run: |
         git flow release start $(date +%Y-%m-%d)
         git push origin release/$(date +%Y-%m-%d)
         gh pr create -B "main" -t "本番リリース" -b "リリース内容を記載してください"
         echo "pull_request_url=$(gh pr view release | grep -o 'https://github.com/[^ ]*' | awk 'NR==1')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: Send custom JSON data to Slack workflow
#       if: steps.create_pr.outcome == 'success'
#       id: slack
#       uses: slackapi/slack-github-action@v1.24.0
#       with:
#         payload: |
#           {
#             "channel": "#times_nakai",
#             "text": "<@${{ secrets.SLACK_TARGET_MENTION }}>本番リリース用のプルリクエストを作成しました。内容を確認してください\n${{ steps.create_pr.outputs.pull_request_url }}"
#           }
#       env:
#         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
